import { describe, expect, it, vi } from 'vitest';
import { PaintInputTool } from './PaintInputTool';

const mouse=(button=0)=>({button} as MouseEvent);
describe('PaintInputTool',()=>{
  it('commits exactly once on mouseup and never during transient movement',()=>{const commit=vi.fn();const tool=new PaintInputTool({} as any,()=>({id:'p',valid:true}),()=>({radiusKm:100,strengthMeters:500,falloff:'hard',mode:'raise'}),()=>6371,commit,vi.fn());tool.onMouseDown(mouse(),[0,0]);tool.onMouseMove(mouse(),[2,0]);expect(commit).not.toHaveBeenCalled();tool.onMouseUp(mouse(),[3,0]);expect(commit).toHaveBeenCalledTimes(1);expect(commit.mock.calls[0][1].length).toBeGreaterThan(1);});
  it('cancels on Escape or tool cancellation without committing',()=>{const commit=vi.fn();const tool=new PaintInputTool({} as any,()=>({id:'p',valid:true}),()=>({radiusKm:100,strengthMeters:500,falloff:'smoothstep',mode:'lower'}),()=>6371,commit,vi.fn());tool.onMouseDown(mouse(),[0,0]);tool.onKeyDown({key:'Escape'} as KeyboardEvent);tool.onMouseUp(mouse(),[1,0]);tool.onMouseDown(mouse(),[0,0]);tool.cancel();tool.onMouseUp(mouse(),[1,0]);expect(commit).not.toHaveBeenCalled();});
  it('rejects invalid or locked owners without a draft',()=>{const reject=vi.fn(),commit=vi.fn();const tool=new PaintInputTool({} as any,()=>({id:'p',valid:false,reason:'locked'}),()=>({radiusKm:100,strengthMeters:500,falloff:'hard',mode:'raise'}),()=>6371,commit,reject);tool.onMouseDown(mouse(),[0,0]);tool.onMouseUp(mouse(),[1,0]);expect(reject).toHaveBeenCalledWith('locked');expect(commit).not.toHaveBeenCalled();});
  it('clips transient support to the selected owner mask',()=>{const path=vi.fn(),projection={getPathGenerator:()=>path,getProjection:()=>({scale:()=>100}),project:()=>[10,10]} as any,clip=vi.fn(),ctx={save:vi.fn(),restore:vi.fn(),beginPath:vi.fn(),clip,arc:vi.fn(),fill:vi.fn(),stroke:vi.fn(),set strokeStyle(_v:string){},set fillStyle(_v:string){},set globalAlpha(_v:number){},set lineCap(_v:string){},set lineJoin(_v:string){},set lineWidth(_v:number){}} as any;const mask=[[[[-20,-20],[-20,20],[20,20],[20,-20],[-20,-20]]]] as any;const tool=new PaintInputTool(projection,()=>({id:'p',valid:true}),()=>({radiusKm:100,strengthMeters:500,falloff:'hard',mode:'raise'}),()=>6371,vi.fn(),vi.fn(),()=>mask);tool.onMouseDown(mouse(),[0,0]);tool.render(ctx);expect(path).toHaveBeenCalledWith({type:'MultiPolygon',coordinates:mask[0]});expect(clip).toHaveBeenCalledTimes(1);});
});
