import { describe, expect, it } from 'vitest';
import { AppState, Coordinate, ElevationZone, TectonicPlate, createDefaultWorldState } from '../types';
import { BACKGROUND_OCEAN_METERS, brushWeight, deriveElevationField, encodeGray16Png, encodeHeightSamples16, encodeHeightSamples8, greatCircleInterpolate, metersToUInt16, metersToUInt8, resampleGreatCirclePath } from './ElevationField';
import { applyElevationZoneAction } from './ElevationZoneActions';

const square = (west: number, east: number, south=-40, north=40): Coordinate[] => [[west,south],[west,north],[east,north],[east,south],[west,south]];
function plate(id='plate', points=square(-40,40), elevation=500): TectonicPlate {
  return { id, name:id, birthTime:0, deathTime:null, elevation, motionSegments:[{time:0,eulerPole:{position:[0,90],rate:0}}], geometryStages:[{time:0,polygons:[{id:`${id}-poly`,points,closed:true}],features:[]}], polygons:[{id:`${id}-poly`,points,closed:true}], features:[], initialPolygons:[{id:`${id}-poly`,points,closed:true}], initialFeatures:[], center:[0,0], connectedRiftIds:[], events:[], visible:true, locked:false } as unknown as TectonicPlate;
}
function zone(ownerPlateId='plate', position:Coordinate=[0,0], deltaMeters=500): ElevationZone {
  return { id:'zone',name:'zone',ownerPlateId,anchorTime:0,activeFrom:0,order:0,operation:'add',visible:true,locked:false,previewColor:'#fff',geometry:{kind:'brush',path:[{position}],radiusKm:1200,deltaMeters,falloff:'smoothstep',spacingKm:200,kernelVersion:1} };
}
function stateAt(position: Coordinate=[0,0], delta=500): AppState {
  const world=createDefaultWorldState(); world.plates=[plate()]; world.elevationZones=[zone('plate',position,delta)];
  return {world,activeTool:'paint',activeFeatureType:'mountain',drawMode:'polygon',activeLineType:'generic',activePolygonType:'generic',viewport:{width:100,height:50,scale:1,rotate:[0,0,0],translate:[0,0]}};
}
function decodeGray16(png:Uint8Array): {width:number;height:number;samples:number[]} {
  const view=new DataView(png.buffer,png.byteOffset,png.byteLength), width=view.getUint32(16), height=view.getUint32(20); const chunks:Uint8Array[]=[];
  for(let at=8;at<png.length;){const length=view.getUint32(at);const type=new TextDecoder().decode(png.subarray(at+4,at+8));if(type==='IDAT')chunks.push(png.slice(at+8,at+8+length));at+=12+length;}
  const packed=new Uint8Array(chunks.reduce((n,c)=>n+c.length,0));let offset=0;for(const c of chunks){packed.set(c,offset);offset+=c.length;}
  const stored:number[]=[];for(let at=2;at<packed.length-4;){const header=packed[at++];expect(header&6).toBe(0);const length=packed[at]|(packed[at+1]<<8);at+=4;stored.push(...packed.subarray(at,at+length));at+=length;if(header&1)break;}const raw=Uint8Array.from(stored), samples:number[]=[];for(let y=0;y<height;y++){expect(raw[y*(1+width*2)]).toBe(0);for(let x=0;x<width;x++)samples.push((raw[y*(1+width*2)+1+x*2]<<8)|raw[y*(1+width*2)+2+x*2]);}
  return {width,height,samples};
}

describe('ElevationField',()=>{
  it('has compact kernels, negative deltas, and no NaNs',()=>{expect(brushWeight(10,10,'hard')).toBe(1);expect(brushWeight(10.01,10,'hard')).toBe(0);expect(brushWeight(0,10,'smoothstep')).toBe(1);expect(brushWeight(10,10,'smoothstep')).toBe(0);expect(Number.isNaN(brushWeight(NaN,10,'smoothstep'))).toBe(false);const field=deriveElevationField(stateAt([0,0],-700),0,{width:72,height:36,includeBase:false});expect(Math.min(...field)).toBeLessThan(-400);expect([...field].every(Number.isFinite)).toBe(true);});
  it('samples great circles across the antimeridian and over a pole',()=>{const points=resampleGreatCirclePath([[179,0],[-179,0]],100,6371);expect(points.length).toBeGreaterThan(2);expect(Math.abs(Math.abs(points[1][0])-180)).toBeLessThan(1);expect(greatCircleInterpolate([0,80],[180,80],.5)[1]).toBeGreaterThan(89);});
  it('stamps across the antimeridian and at both poles',()=>{const cases:[Coordinate,Coordinate[]][]=[[[179,0],[[160,-40],[160,40],[-160,40],[-160,-40],[160,-40]]],[[0,88],[[-180,70],[180,70],[60,70],[-60,70],[-180,70]]],[[0,-88],[[-180,-70],[-60,-70],[60,-70],[180,-70],[-180,-70]]]];for(const [position,mask] of cases){const state=stateAt(position);state.world.plates=[plate('plate',mask)];const field=deriveElevationField(state,0,{width:72,height:36,includeBase:false});expect(Math.max(...field)).toBeGreaterThan(100);}const state=stateAt([179,0]);state.world.plates=[plate('plate',cases[0][1])];const seam=deriveElevationField(state,0,{width:72,height:36,includeBase:false});expect(Math.max(...Array.from({length:36},(_,y)=>seam[y*72]))).toBeGreaterThan(0);expect(Math.max(...Array.from({length:36},(_,y)=>seam[y*72+71]))).toBeGreaterThan(0);});
  it('starts with deep-ocean background, then adds derived plate and feature relief',()=>{const state=stateAt();state.world.plates[0].features=[{id:'m',type:'mountain',position:[0,0],rotation:0,scale:1,properties:{}}];state.world.plates[0].geometryStages[0].features=state.world.plates[0].features;state.world.elevationZones=[];const field=deriveElevationField(state,0,{width:360,height:180});expect(Math.max(...field)).toBeGreaterThan(1000);expect(Math.min(...field)).toBe(BACKGROUND_OCEAN_METERS);});
  it('uses deterministic order/id, visibility, lock neutrality, and half-open time',()=>{const state=stateAt();state.world.elevationZones.push({...zone(),id:'aaa',order:0,geometry:{...(zone().geometry as any),deltaMeters:250}});const a=deriveElevationField(state,0,{width:72,height:36,includeBase:false}), b=deriveElevationField(state,0,{width:72,height:36,includeBase:false});expect([...a]).toEqual([...b]);expect(Math.max(...a)).toBeGreaterThan(500);state.world.elevationZones[0].locked=true;expect([...deriveElevationField(state,0,{width:72,height:36,includeBase:false})]).toEqual([...a]);state.world.elevationZones[0].activeTo=0;expect(Math.max(...deriveElevationField(state,0,{width:72,height:36,includeBase:false}))).toBeLessThan(Math.max(...a));state.world.elevationZones.forEach(z=>z.visible=false);expect(Math.max(...deriveElevationField(state,0,{width:72,height:36,includeBase:false}))).toBe(0);});
  it('keeps every derived sample finite after rejected extreme zone edits',()=>{const state=stateAt();for(const edit of [{radiusKm:1e300,deltaMeters:500,falloff:'hard' as const},{radiusKm:100,deltaMeters:1e39,falloff:'hard' as const}]){const result=applyElevationZoneAction(state.world.elevationZones,'zone',{type:'edit',...edit});expect(result.changed).toBe(false);state.world.elevationZones=result.zones;}expect([...deriveElevationField(state,0,{width:144,height:72})].every(Number.isFinite)).toBe(true);});
  it('maps 16-bit and directly-rounded 8-bit scales exactly and rejects invalid ranges',()=>{expect(metersToUInt16(-11000)).toBe(0);expect(metersToUInt16(9000)).toBe(65535);expect([...encodeHeightSamples16(new Float32Array([-11000,9000]))]).toEqual([0,65535]);expect(metersToUInt8(-11000)).toBe(0);expect(metersToUInt8(9000)).toBe(255);expect([...encodeHeightSamples8(new Float32Array([-11000,-1000,9000]))]).toEqual([0,128,255]);expect(()=>metersToUInt16(0,{minMeters:1,maxMeters:1})).toThrow(/minimum/);});
  it('decodes an exact 16-bit grayscale PNG payload',()=>{const png=encodeGray16Png(new Uint16Array([0,1,32768,65535]),2,2);expect([...png.slice(0,8)]).toEqual([137,80,78,71,13,10,26,10]);expect(png[24]).toBe(16);expect(png[25]).toBe(0);expect(decodeGray16(png)).toEqual({width:2,height:2,samples:[0,1,32768,65535]});});
});
