import { describe, expect, it } from 'vitest';
import { HistoryManager } from '../HistoryManager';
import { rebaseWorldFromCurrentTime } from '../export';
import { remapImportedWorld } from '../importHelpers';
import { CURRENT_SAVE_VERSION, migrateSaveFile } from '../migration';
import { AppState, Coordinate, ElevationZone, TectonicPlate, createDefaultWorldState } from '../types';
import { deriveElevationField } from './ElevationField';

const ring:Coordinate[]=[[-40,-30],[-40,30],[40,30],[40,-30],[-40,-30]];
function fixture():AppState{const world=createDefaultWorldState();const polygons=[{id:'poly',points:ring,closed:true}];const plate={id:'p',name:'p',birthTime:0,deathTime:null,motionSegments:[{time:0,eulerPole:{position:[0,90],rate:1}}],geometryStages:[{time:0,polygons,features:[]}],polygons,features:[],initialPolygons:polygons,initialFeatures:[],center:[0,0],connectedRiftIds:[],events:[],visible:true,locked:false} as unknown as TectonicPlate;const zone:ElevationZone={id:'root',name:'z',ownerPlateId:'p',anchorTime:0,activeFrom:0,order:0,operation:'add',visible:true,locked:false,previewColor:'#fff',geometry:{kind:'brush',path:[{position:[0,0]}],radiusKm:900,deltaMeters:500,falloff:'hard',spacingKm:100,kernelVersion:1}};world.plates=[plate];world.elevationZones=[zone];world.currentTime=10;return {world,activeTool:'paint',activeFeatureType:'mountain',drawMode:'polygon',activeLineType:'generic',activePolygonType:'generic',viewport:{width:1,height:1,scale:1,rotate:[0,0,0],translate:[0,0]}};}

describe('elevation persistence',()=>{
  it('migrates v9 saves to an empty elevation collection',()=>{const raw:any={version:9,world:createDefaultWorldState()};delete raw.world.elevationZones;migrateSaveFile(raw);expect(raw.version).toBe(CURRENT_SAVE_VERSION);expect(raw.world.elevationZones).toEqual([]);});
  it('history snapshots deeply isolate stroke paths and masks',()=>{const state=fixture();state.world.elevationZones[0].geometry={...(state.world.elevationZones[0].geometry as any),clipMask:[[ring]]};const history=new HistoryManager();history.push(state);(state.world.elevationZones[0].geometry as any).path[0].position[0]=99;(state.world.elevationZones[0].geometry as any).clipMask[0][0][0][0]=99;const restored=history.undo(state)!;expect((restored.world.elevationZones[0].geometry as any).path[0].position[0]).toBe(0);expect((restored.world.elevationZones[0].geometry as any).clipMask[0][0][0][0]).toBe(-40);});
  it('merge import remaps group and zone lineage references in two passes',()=>{const state=fixture();state.world.entityGroups=[{id:'g',name:'g',type:'plate',expanded:true} as any];state.world.elevationZones=[{...state.world.elevationZones[0],groupId:'g'},{...state.world.elevationZones[0],id:'fragment',lineageId:'root',groupId:'g'}];const result=remapImportedWorld(state.world,0);const importedRoot=result.elevationZones.find(zone=>!zone.lineageId)!;const fragment=result.elevationZones.find(zone=>zone.lineageId)!;expect(importedRoot.id).not.toBe('root');expect(fragment.lineageId).toBe(importedRoot.id);expect(fragment.groupId).toBe(result.entityGroups[0].id);});
  it('from-current-time rebasing preserves the field in a new zero-time frame',()=>{const state=fixture();const before=deriveElevationField(state,10,{width:144,height:72,includeBase:false});const rebased={...state,world:rebaseWorldFromCurrentTime(state)};const after=deriveElevationField(rebased,0,{width:144,height:72,includeBase:false});expect(rebased.world.elevationZones[0].anchorTime).toBe(0);expect(rebased.world.elevationZones[0].activeFrom).toBe(0);expect([...after]).toEqual([...before]);});
});
