import {expect,it} from 'vitest';import {AppState,Coordinate,TectonicPlate,createDefaultWorldState} from '../types';import {deriveElevationField,encodeGray16Png,encodeHeightSamples16} from './ElevationField';
const enabled=(globalThis as any).process?.env?.TECTOLITE_HEIGHTMAP_BENCHMARK==='1';
function makePlate(id:string,points:Coordinate[],feature?:Coordinate):TectonicPlate{const polygons=[{id:`${id}-poly`,points,closed:true}],features=feature?[{id:`${id}-mountain`,type:'mountain' as const,position:feature,rotation:0,scale:1.5,properties:{}}]:[];return {id,name:id,birthTime:0,deathTime:null,motionSegments:[{time:0,eulerPole:{position:[0,90],rate:.15}}],geometryStages:[{time:0,polygons,features}],polygons,features,initialPolygons:polygons,initialFeatures:features,center:feature||points[0],connectedRiftIds:[],events:[],visible:true,locked:false} as unknown as TectonicPlate;}
it.runIf(enabled)('enforces the representative 4096x2048 canonical export gate',()=>{const world=createDefaultWorldState();world.plates=[makePlate('west',[[-170,-60],[-170,60],[-20,60],[-20,-60],[-170,-60]],[-90,20]),makePlate('east',[[-20,-60],[-20,60],[130,60],[130,-60],[-20,-60]],[50,-10]),makePlate('seam',[[130,-60],[130,60],[-170,60],[-170,-60],[130,-60]],[170,0]),makePlate('polar',[[-180,60],[180,60],[60,60],[-60,60],[-180,60]],[0,82])];const paths:Record<string,Coordinate[][]>={west:[[[-150,-30],[-45,35]],[[-130,40],[-60,-35]]],east:[[[0,-35],[100,30]],[[20,35],[115,-20]]],seam:[[[150,-20],[-178,25]],[[175,35],[-155,-30]]],polar:[[[-120,75],[20,87],[120,75]],[[170,78],[-170,80]]]} ;let order=0;world.elevationZones=world.plates.flatMap(plate=>paths[plate.id].map((path,index)=>({id:`zone-${plate.id}-${index}`,name:'zone',ownerPlateId:plate.id,anchorTime:0,activeFrom:0,order:order++,operation:'add' as const,visible:true,locked:false,previewColor:'#fff',geometry:{kind:'brush' as const,path:path.map(position=>({position})),radiusKm:220+index*180,deltaMeters:index? -350:650,falloff:'smoothstep' as const,spacingKm:55,kernelVersion:1 as const}})));const state={world,activeTool:'paint',activeFeatureType:'mountain',drawMode:'polygon',activeLineType:'generic',activePolygonType:'generic',viewport:{width:1,height:1,scale:1,rotate:[0,0,0],translate:[0,0]}} as AppState;
  const started=performance.now(),cloned=structuredClone(state),clonedAt=performance.now();
  const field=deriveElevationField(cloned,cloned.world.currentTime,{width:4096,height:2048}),derivedAt=performance.now();
  const samples=encodeHeightSamples16(field),quantizedAt=performance.now();
  const png=encodeGray16Png(samples,4096,2048),encodedAt=performance.now(),elapsed=encodedAt-started;
  (globalThis as any).process?.stdout?.write(`TECTOLITE_HEIGHTMAP_BENCHMARK_MS=${elapsed.toFixed(1)} CLONE_MS=${(clonedAt-started).toFixed(1)} DERIVE_MS=${(derivedAt-clonedAt).toFixed(1)} QUANTIZE_MS=${(quantizedAt-derivedAt).toFixed(1)} PNG_MS=${(encodedAt-quantizedAt).toFixed(1)} PNG_BYTES=${png.byteLength} PLATES=${world.plates.length} STROKES=${world.elevationZones.length}\n`);expect(png.byteLength).toBeGreaterThan(16_000_000);expect(elapsed).toBeLessThan(5000);
},20_000);
