import { describe, expect, it } from 'vitest';
import { AppState, Coordinate, ElevationZone, TectonicPlate, createDefaultWorldState } from '../types';
import { deriveElevationField } from './ElevationField';
import { derivePlateGeometry } from '../motion/RotationModel';
import { greatCircleDistanceToSegmentKm, recomputeFusionTransfer, recomputeSplitTransfer, removeFusionTransfer, removeSplitTransfer, transferZonesForFusion, transferZonesForSplit } from './ElevationZoneLifecycle';

const ring=(west:number,east:number):Coordinate[]=>[[west,-30],[west,30],[east,30],[east,-30],[west,-30]];
function plate(id:string,west:number,east:number,birth=0,death:number|null=null,parents?:string[]):TectonicPlate{const polygons=[{id:`${id}-p`,points:ring(west,east),closed:true}];return {id,name:id,birthTime:birth,deathTime:death,parentPlateIds:parents,motionSegments:[{time:birth,eulerPole:{position:[0,90],rate:0}}],geometryStages:[{time:birth,polygons,features:[]}],polygons,features:[],initialPolygons:polygons,initialFeatures:[],center:[(west+east)/2,0],connectedRiftIds:[],events:[],visible:true,locked:false} as unknown as TectonicPlate;}
function source(owner='parent',activeTo:number|undefined=30):ElevationZone{return {id:'z',name:'z',ownerPlateId:owner,anchorTime:0,activeFrom:0,activeTo,order:0,operation:'add',visible:true,locked:false,previewColor:'#fff',geometry:{kind:'brush',path:[{position:[-20,0]},{position:[20,0]}],radiusKm:700,deltaMeters:500,falloff:'hard',spacingKm:150,kernelVersion:1}};}
function app(plates:TectonicPlate[],zones:ElevationZone[]):AppState{const world=createDefaultWorldState();world.plates=plates;world.elevationZones=zones;return {world,activeTool:'paint',activeFeatureType:'mountain',drawMode:'polygon',activeLineType:'generic',activePolygonType:'generic',viewport:{width:1,height:1,scale:1,rotate:[0,0,0],translate:[0,0]}};}

describe('ElevationZoneLifecycle',()=>{
  it('keeps a dot fragment when brush support crosses a long edge',()=>{const parent=plate('parent',-40,40,0,10),left=plate('left',-40,0,10),right=plate('right',0,40,10);const dot={...source('parent',undefined),geometry:{kind:'brush' as const,path:[{position:[-1,0] as Coordinate}],radiusKm:200,deltaMeters:500,falloff:'hard' as const,spacingKm:50,kernelVersion:1 as const}};const fragments=transferZonesForSplit([dot],parent,[left,right],[parent,left,right],10).filter(zone=>zone.lineageId==='z');expect(fragments.map(zone=>zone.ownerPlateId).sort()).toEqual(['left','right']);expect(greatCircleDistanceToSegmentKm([-1,0],[0,-30],[0,30],6371)).toBeLessThan(200);});
  it('is seam-safe for antimeridian child masks',()=>{const parent=plate('parent',160,-160,0,10),east=plate('east',160,180,10),west=plate('west',-180,-160,10);const dot={...source('parent',undefined),geometry:{kind:'brush' as const,path:[{position:[179,0] as Coordinate}],radiusKm:300,deltaMeters:500,falloff:'hard' as const,spacingKm:75,kernelVersion:1 as const}};const fragments=transferZonesForSplit([dot],parent,[east,west],[parent,east,west],10).filter(zone=>zone.lineageId==='z');expect(fragments.map(zone=>zone.ownerPlateId).sort()).toEqual(['east','west']);expect(greatCircleDistanceToSegmentKm([179,0],[180,-30],[180,30],6371)).toBeLessThan(300);});
  it('is pole-safe for converging split edges',()=>{const northRing:Coordinate[]=[[-180,70],[180,70],[60,70],[-60,70],[-180,70]],westRing:Coordinate[]=[[-180,70],[0,90],[0,70],[-60,70],[-180,70]],eastRing:Coordinate[]=[[0,70],[0,90],[180,70],[60,70],[0,70]];const parent=plate('parent',-1,1,0,10),west=plate('west',-1,0,10),east=plate('east',0,1,10);for(const [p,r] of [[parent,northRing],[west,westRing],[east,eastRing]] as [TectonicPlate,Coordinate[]][]){p.polygons[0].points=r;p.geometryStages[0].polygons[0].points=r;p.initialPolygons[0].points=r;}const dot={...source('parent',undefined),geometry:{kind:'brush' as const,path:[{position:[0,88] as Coordinate}],radiusKm:350,deltaMeters:500,falloff:'hard' as const,spacingKm:80,kernelVersion:1 as const}};const fragments=transferZonesForSplit([dot],parent,[west,east],[parent,west,east],10).filter(zone=>zone.lineageId==='z');expect(fragments.map(zone=>zone.ownerPlateId).sort()).toEqual(['east','west']);expect(greatCircleDistanceToSegmentKm([0,88],[0,70],[0,90],6371)).toBe(0);});
  it('creates only non-empty disjoint split fragments and preserves the end time',()=>{const parent=plate('parent',-40,40,0,10),left=plate('left',-40,0,10),right=plate('right',0,40,10),far=plate('far',100,120,10);const zones=transferZonesForSplit([source()],parent,[left,right,far],[parent,left,right,far],10);expect(zones.find(z=>z.id==='z')?.activeTo).toBe(10);const fragments=zones.filter(z=>z.lineageId==='z');expect(fragments.map(z=>z.ownerPlateId).sort()).toEqual(['left','right']);expect(fragments.every(z=>z.activeFrom===10&&z.activeTo===30&&z.geometry.clipMask?.length)).toBe(true);expect(new Set(fragments.map(z=>z.id)).size).toBe(2);});
  it('keeps the authored field continuous across split and fusion frames',()=>{const parent=plate('parent',-40,40,0,10),left=plate('left',-40,0,10,20),right=plate('right',0,40,10,20);let zones=transferZonesForSplit([source('parent',undefined)],parent,[left,right],[parent,left,right],10);const before=deriveElevationField(app([parent,left,right],zones),9.999,{width:144,height:72,includeBase:false});const after=deriveElevationField(app([parent,left,right],zones),10,{width:144,height:72,includeBase:false});expect(Math.max(...after)).toBe(Math.max(...before));expect(after.reduce((n,v)=>n+(v!==0?1:0),0)).toBe(before.reduce((n,v)=>n+(v!==0?1:0),0));const fused=plate('fused',-40,40,20,null,['left','right']);zones=transferZonesForFusion(zones,[left,right],fused,[parent,left,right,fused],20);const preFusion=deriveElevationField(app([parent,left,right,fused],zones),19.999,{width:144,height:72,includeBase:false});const postFusion=deriveElevationField(app([parent,left,right,fused],zones),20,{width:144,height:72,includeBase:false});expect(postFusion.reduce((n,v)=>n+v,0)).toBeCloseTo(preFusion.reduce((n,v)=>n+v,0),3);expect(zones.filter(z=>z.ownerPlateId==='fused')).toHaveLength(2);});
  it('recomputes retimed transfers and restores sources on deletion',()=>{const parent=plate('parent',-40,40,0,10),left=plate('left',-40,0,10),right=plate('right',0,40,10);let zones=transferZonesForSplit([source()],parent,[left,right],[parent,left,right],10);left.birthTime=right.birthTime=12;parent.deathTime=12;zones=recomputeSplitTransfer(zones,parent,[left,right],[parent,left,right],10,12);expect(zones.find(z=>z.id==='z')?.activeTo).toBe(12);expect(zones.filter(z=>z.lineageId==='z').every(z=>z.activeFrom===12)).toBe(true);zones=removeSplitTransfer(zones,[left,right],12);expect(zones).toHaveLength(1);expect(zones[0].activeTo).toBe(30);});
  it('derives retimed child masks in the new moving frame',()=>{const parent=plate('parent',-40,40,0,10),left=plate('left',-40,0,10),right=plate('right',0,40,10);for(const p of [parent,left,right])p.motionSegments[0].eulerPole.rate=1;let zones=transferZonesForSplit([source('parent',undefined)],parent,[left,right],[parent,left,right],10);const old=(zones.find(z=>z.ownerPlateId==='left')!.geometry.clipMask![0][0][0]);left.birthTime=right.birthTime=12;parent.deathTime=12;zones=recomputeSplitTransfer(zones,parent,[left,right],[parent,left,right],10,12);const moved=zones.find(z=>z.ownerPlateId==='left')!.geometry.clipMask![0][0][0],expected=derivePlateGeometry(left,[parent,left,right],12).polygons[0].points[0];expect(moved[0]).not.toBeCloseTo(old[0],5);expect(moved[0]).toBeCloseTo(expected[0],8);expect(moved[1]).toBeCloseTo(expected[1],8);});
  it('reanchors masks through moving fusion retime and removes fragments cleanly',()=>{const left=plate('left',-40,0,0,20),right=plate('right',0,40,0,20),fused=plate('fused',-40,40,20,null,['left','right']);left.motionSegments[0].eulerPole.rate=right.motionSegments[0].eulerPole.rate=1;const clipped={...source('left'),geometry:{...(source('left').geometry as any),clipMask:[[ring(-40,0)]]}} as ElevationZone;let zones=transferZonesForFusion([clipped],[left,right],fused,[left,right,fused],20);const old=zones.find(z=>z.ownerPlateId==='fused')!.geometry.clipMask![0][0][0][0];fused.birthTime=22;left.deathTime=right.deathTime=22;zones=recomputeFusionTransfer(zones,[left,right],fused,[left,right,fused],20,22);const fragment=zones.find(z=>z.ownerPlateId==='fused')!;expect(fragment.anchorTime).toBe(22);expect(fragment.geometry.clipMask![0][0][0][0]).not.toBeCloseTo(old,5);zones=removeFusionTransfer(zones,fused,22);expect(zones).toHaveLength(1);expect(zones[0].activeTo).toBe(30);});
});
